name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
      - run: make docker-build
        if: steps.semrel.outputs.version == ''
      - name: Login to GitHub Container Registry
        if: steps.semrel.outputs.version != ''
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: make docker-build docker-push VERSION=${{steps.semrel.outputs.version}}
        if: steps.semrel.outputs.version != ''
